apiVersion: v1
kind: ServiceAccount
metadata:
  name: kuscale
  namespace: default

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kuscale
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kuscale
subjects:
- kind: ServiceAccount
  name: kuscale
  namespace: default
roleRef:
  kind: ClusterRole
  name: kuscale
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kuscale-daemonset
  namespace: default #kube-system
spec:
  selector:
    matchLabels:
      name: kuscale-ds
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        name: kuscale-ds
    spec:
      serviceAccountName: kuscale
      hostNetwork: true  
      # serviceAccount: kuscale
      # imagePullSecrets:
      # - name: regcred
      containers:
      # - image: guswns531/kuscale:base-${VERSION}
      - image: guswns531/kuscale:base-9
        name: kuscale
        # command: ["./bin/kuscale", "-v", "1", "--MonitoringPeriod", "2", "--MonitoringMode", "false"]
        securityContext:
            privileged: true
            capabilities:
              add:
                - all
        volumeMounts:
          - name: pod-resources
            mountPath: /var/lib/kubelet/pod-resources
          - name: device-plugin
            mountPath: /kubeshare
          - name: kubelet
            mountPath: /var/lib/kubelet/
          - name: cgroup
            mountPath: /home/cgroup
          - name: sys-kenel
            mountPath: /sys/kernel/
          - name: run-dir
            mountPath: /var/run
          - name: host-dev
            mountPath: /dev
          - name: host-modules
            mountPath: /lib/modules
          - name: host-proc
            mountPath: /home/proc
          - name: kuscale
            mountPath: /KuScale
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
      volumes:
        - name: pod-resources
          hostPath:
            path: /var/lib/kubelet/pod-resources
        - name: device-plugin
          hostPath:
            path: /kubeshare
        - name: kubelet
          hostPath:
            path: /var/lib/kubelet/
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: sys-kenel
          hostPath:
            path: /sys/kernel/
        - name: run-dir
          hostPath:
            type: Directory
            path: /var/run
        - name: host-dev
          hostPath:
            type: Directory
            path: /dev
        - name: host-modules
          hostPath:
            type: Directory
            path: /lib/modules
        - name: host-proc
          hostPath:
            type: Directory
            path: /proc
        - name: kuscale
          hostPath:
            type: Directory
            path: /home/sslab/KuScale
        
