apiVersion: batch/v1
kind: Job
metadata:
  name: matrix
spec:
  template:
    spec:
      nodeSelector:
        type1: gpu1
      tolerations:
      - key: worker
        value: gpu
        operator: Equal
        effect: NoExecute
      hostIPC: true
      restartPolicy: Never
      containers:
      - image: docker.io/guswns531/jobs:matrix-004
        name: matrix
        # command:  ["sleep", "50000"]
        command:  ["./time", "./matrix", "2048", "4000"]
        resources:
          limits:
            kuscale.com/token: 600
        volumeMounts:
          - name: shmdir
            mountPath: /dev/shm             
      volumes:
        - name: shmdir
          emptyDir:
            medium: Memory
            sizeLimit: "1G"