apiVersion: batch/v1
kind: Job
metadata:
  name: test
spec:
  template:
    spec:
      hostIPC: true
      restartPolicy: Never
      containers:
      - image: docker.io/guswns531/jobs:yolov5-flask-004
      # - image: docker.io/guswns531/jobs:matrix-001
        ports:
          - containerPort: 5000
        name: test
        # command:  ["/bin/bash", "-c", "python", "restapi.py", "--port=5000"]
        command:  ["sleep", "50000"]
        resources:
          limits:
            kuscale.com/token: 1
        volumeMounts:
          - name: shmdir
            mountPath: /dev/shm             
      volumes:
        - name: shmdir
          emptyDir:
            medium: Memory
            sizeLimit: "1G"