apiVersion: batch/v1
kind: Job
metadata:
  name: test3
spec:
  template:
    spec:
      hostIPC: true
      restartPolicy: Never
      containers:
      # - image: docker.io/guswns531/jobs:yolov5-flask-004
      - image: docker.io/guswns531/jobs:matrix-004
      # - image: nvcr.io/nvidia/pytorch:21.03-py3
        name: test3
        # command:  ["/bin/bash", "-c", "python", "restapi.py", "--port=5000"]
        # command:  ["sleep", "50000"]
        command:  ["./time", "./matrix", "2048", "4000"]
        resources:
          limits:
            kuscale.com/token: 1
        volumeMounts:
          - name: shmdir
            mountPath: /dev/shm             
      volumes:
        - name: shmdir
          emptyDir:
            medium: Memory
            sizeLimit: "1G"