apiVersion: batch/v1
kind: Job
metadata:
  name: yolov5-02
spec:
  template:
    spec:
      hostIPC: true
      restartPolicy: Never
      containers:
      # - image: docker.io/guswns531/jobs:yolov5-flask-004
      - image: guswns531/jobs:yolov5-009
        name: yolov5-02
        # command:  ["/bin/bash", "-c", "python", "restapi.py", "--port=5000"]
        # command:  ["sleep", "50000"]
        command:  ["./time", "/opt/conda/bin/python3", "detect.py", "--weights", "yolov5l.pt", "--source", "2160p_30fps_30s.mp4", "--nosave"]
        # command:  ["./matrix", "2048", "2000"]
        resources:
          limits:
            kuscale.com/token: 1
        volumeMounts:
          - name: shmdir
            mountPath: /dev/shm             
      volumes:
        - name: shmdir
          emptyDir:
            medium: Memory
            sizeLimit: "1G"


# ./time python3 detect.py --weights yolov5l.pt --source 2160p_30fps_30s.mp4 --nosave