apiVersion: v1
kind: PersistentVolume
metadata:
  name: kuscale-nfs-pv
spec:
  capacity:
    storage: 10Gi
  claimRef:
     namespace: default
     name: kuscale-pvc
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /volume5/hyeonjun-nfs/KuScale
    server: 117.16.143.10
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuscale-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi