# prometheus-config-map.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.yml: |-
    global:
      scrape_interval: 2s
      evaluation_interval: 2s
    scrape_configs:
      - job_name: 'dorry container exporter'
        scrape_interval: 1s
        scrape_timeout: 1s
        scheme: http
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
        - source_labels: [__meta_kubernetes_endpoints_name]
          regex: 'kuscale-svc'
          action: keep
      # - job_name: 'cadvisor'
      #   scrape_interval: 5s
      #   scrape_timeout: 5s
      #   scheme: http
      #   metrics_path: /metrics
      #   kubernetes_sd_configs:
      #     - role: endpoints
      #   relabel_configs:
      #   - source_labels: [__meta_kubernetes_endpoints_name]
      #     regex: 'cadvisor-service'
      #     action: keep
      # - job_name: gpu-metrics
      #   scrape_interval: 1s
      #   metrics_path: /metrics
      #   scheme: http
      #   kubernetes_sd_configs:
      #   - role: endpoints
      #   relabel_configs:
      #   - source_labels: [__meta_kubernetes_pod_container_name]
      #     action: keep
      #     target_label: dcgm-exporter
